# -*- coding:UTF-8 -*-
from enum import Enum

#基本牌型
CardType = Enum('CardType', (
    'CARDTYPE_NODE_BOMB_TWO',    
    'CARDTYPE_NODE_BOMB', 
    'CARDTYPE_NODE_THREEPROGRESS', 
    'CARDTYPE_NODE_PROGRESS', 
    'CARDTYPE_NODE_LINKPAIR', 
    'CARDTYPE_NODE_THREEITEM', 
    'CARDTYPE_NODE_PAIR', 
    'CARDTYPE_NODE_SINGLECARD', 
    'CARDTYPE_NODE_MAX'))

#出牌类型
OT = Enum('OT', (
    'CARDTYPE_BOMB',
    'CARDTYPE_FOURANDTWO_ONE',
    'CARDTYPE_FOURANDTWO_TWO',
    'CARDTYPE_THREEPROGRESS',
    'CARDTYPE_THREEPROGRESS_ONE',
    'CARDTYPE_THREEPROGRESS_TWO',
    'CARDTYPE_PROGRESS',
    'CARDTYPE_THREEITEM',
    'CARDTYPE_THREEITEM_ONE',
    'CARDTYPE_THREEITEM_TWO',
    'CARDTYPE_LINKPAIR',
    'CARDTYPE_PAIR',
    'CARDTYPE_SINGLECARD',
    'CARDTYPE_MAX'))



